# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    voitures_images_directory: '%kernel.project_dir%/public/uploads/voitures'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
